settings:
  lib_name: nor2b_sky130_tt_1v80_025C_schematic
  results_dir: output
  temperature: 25

  named_nodes:
    primary_power:
      name: VDD
      voltage: 1.8
    primary_ground:
      name: VSS
      voltage: 0.0

cells:
  nor2b:
    netlist: "cells/nor2b.spice"
    area: 109.9189
    models:
      - "config/mc_switches.spice"
      - "sky130A/libs.tech/ngspice/sky130.lib.spice tt"
    data_slews: [0.01, 0.05, 0.1, 0.2]
    loads: [0.001, 0.005, 0.01, 0.05]
    functions:
      - "Y = (A & !B)"